# https://alacritty.org/config-alacritty.html
[shell]
program = "ubuntu.exe"
args = ["run", "(tmux a || tmux new -c ~ )"]


[font]
size= 11
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Light"






