set -g status-justify "left"
set -g status "on"
set -g status-position "top"
set -g status-left-style "none"
set -g message-command-style "fg=colour231,bg=colour31"
set -g status-right-style "none"
set -g pane-active-border-style "fg=blue"
set -g message-style "fg=colour231,bg=colour31"
set -g pane-border-style "fg=default"
set -g status-style "bg=colour232"
set -g message-style "fg=colour231,bg=colour31"
set -g pane-border-style "fg=default"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=colour250,bg=colour232"

# set -g status-left "#[fg=colour16,bg=default] 💖 #[fg=colour254,bg=colour232,nobold,nounderscore,noitalics]"
# set -g status-right "#(/home/linuxbrew/.linuxbrew/bin/rainbarf --width 30 --no-battery --rgb --bright)#[fg=colour236,bg=colour232,nobold,nounderscore,noitalics]#[fg=colour253,bg=colour232] %Y-%m-%d %H:%M #{weather}"
# setw -g window-status-format " #[fg=colour244,bg=default] #I#[fg=colour250,bg=colour232] #W  "
# setw -g window-status-current-format "#[fg=colour232,bg=colour31]#[fg=colour117,bg=colour31] #I #[fg=colour231,bg=colour31,bold] #W #[fg=colour31,bg=default,nobold,nounderscore,noitalics]"


