column_width = 120
line_endings = "Unix"
indent_type = "Spaces"              # "Tabs|Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never" # "Never|Always"

[sort_requires]
enabled = false
