return {
  { "andymass/vim-matchup" },
  { "echasnovski/mini.nvim", version = "*" },
  { "folke/trouble.nvim", cmd = "TroubleToggle" },
  { "folke/which-key.nvim", event = "VeryLazy" },
  { "godlygeek/tabular" },
  { "heavenshell/vim-jsdoc", build = "make install" },
  { "kylechui/nvim-surround", opts = {}, event = "VeryLazy" },
  { "mbbill/undotree" },
  { "mg979/vim-visual-multi" },
  { "nvim-lua/plenary.nvim" },
  { "nvim-tree/nvim-web-devicons" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "simeji/winresizer" },
  { "sphamba/smear-cursor.nvim" },
  { "stevearc/dressing.nvim", event = "VeryLazy" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-repeat" },
  {
    "norcalli/nvim-colorizer.lua",
    ft = { "css", "scss", "html", "javascript", "javascriptreact", "typescript", "typescriptreact" },
    opts = { "*", css = { css = true, css_fn = true } },
  },
  {
    "razak17/tailwind-fold.nvim",
    ft = { "html", "svelte", "astro", "vue", "typescriptreact", "php", "blade" },
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
}
